apiVersion: v1
kind: Service
metadata:
  name: azurite
spec:
  ports:
  - port: 10000
  - port: 10001
  - port: 10002
  selector:
    app: azurite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
        - containerPort: 10000
          name: blob
        - containerPort: 10001
          name: table
        - containerPort: 10002
          name: queue
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-connection-string
type: Opaque
data:
  AzureConnectionString: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU7RGV2ZWxvcG1lbnRTdG9yYWdlUHJveHlVcmk9aHR0
cDovL2F6dXJpdGU=